on: 
 watch:
   types: [started]
name: build apk
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - run: flutter build apk
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: 新建一个Github Release
      id: create-new-release
      uses: actions.create-release@v1
      env:
        GITHUB_TOKEN:${{secrets.GitHUB_TOKEN}}
      with:
        tag_name: v${{github.run_number}}    
        release_name: Release V${{github.run_number}}    
    - name: 开上传文件至release
      uses: actions/upload-release-asset@v1
      env: 
        GITHUB_TOKEN:${{secrets.GitHUB_TOKEN}}
      with:
        upload_url: ${{steps.create-new-release.outputs.upload_url}}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: site-v${{github.run_number}}.apk
        #asset_content_type: application/zip

