on: 
 watch:
   types: [started]
name: build apk
jobs:
  build:
    name: 基于ubuntu-latest安装依赖
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - run: flutter build apk
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
